<a href="https://colab.research.google.com/github/HemaBatraju06/45-Day-Machine-Learning-Journey/blob/main/day11_numpy_advance_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

          Numpy Adavced(Mathmatical operattions  and Broadcasting)

Mathmatical operations: In numpy mathmatical operations are directly applies on the array
*   Addition
*   Substration
*   Multiplication
*   Division




In [ ]:
import numpy as np
a=np.array([2,5,7])
print(a+5)

[ 7 10 12]


Broadcasting : It automatically applies operations to all elements of an arrays

Practice programs


In [ ]:
import numpy as np
a=np.array([2,5,7,9,0,1])
print(a)

[2 5 7 9 0 1]


In [ ]:
#addition
print(a+5)

[ 7 10 12 14  5  6]


In [ ]:
#substraction
print(a-7)

[-5 -2  0  2 -7 -6]


In [ ]:
#multiplication
print( a*3)

[ 6 15 21 27  0  3]


In [ ]:
#Division
print(a/2)

[1.  2.5 3.5 4.5 0.  0.5]


In [ ]:
# array to array operations
import numpy as np
a=np.array([2,5,9])
b=np.array([1,2,3])
print("add:",a+b)
print("sub:",a-b)
print("mul:",a*b)
print("div:",a/b)

add: [ 3  7 12]
sub: [1 3 6]
mul: [ 2 10 27]
div: [2.  2.5 3. ]


In [ ]:
#mean function
a=np.array([2,5,9])
print(np.mean(a))

5.333333333333333


In [ ]:
#sum function
a=np.array([2,5,9])
print(np.sum(a))

16


In [ ]:
#max func
a=np.array([2,5,9])
print(np.max(a))

9


In [ ]:
#min func
a=np.array([2,5,9])
print(np.min(a))

2


Mini task : take student marks and find total ,avg ,highest , lowest marks

In [ ]:
import numpy as np
marks=np.array([60,70,80,90,95])
print("total marks:",np.sum(marks))
print("avg marks:",np.mean(marks))
print("highest marks:",np.max(marks))
print("lowest marks:",np.min(marks))

total marks: 395
avg marks: 79.0
highest marks: 95
lowest marks: 60
