<a href="https://colab.research.google.com/github/HemaBatraju06/45-Day-Machine-Learning-Journey/blob/main/day10_numpy_basics_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                              **Numpy Basics**

Array : Collection of values stored in a single variable

In [ ]:
import numpy as np
data=np.array([1,2,3,4,5]) # array created
print(data)

[1 2 3 4 5]


Indexing : access the elements

In [ ]:
import numpy as np
data=np.array([1,2,3,4,5]) # array created
print(data[2])

3


In [ ]:
# negative indexing

import numpy as np
data=np.array([1,2,3,4,5]) # array created
print(data[-3])

3


Silicing : Access multiple elements


In [ ]:
import numpy as np
data=np.array([1,2,3,4,5]) # array created
print(data[:4])

[1 2 3 4]


 Practice programs :

In [ ]:
# student marks
import numpy as np
marks=np.array([60,45,50,35,65])
print(marks)


[60 45 50 35 65]


In [ ]:
#check type
import numpy as np
arr=np.array([1,3,5,6])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# create array
import numpy as np
data=np.array([5,10,15,20,25])
print(data)

[ 5 10 15 20 25]


In [ ]:
# indexing
print(data[3])

20


In [ ]:
#silicing
print(data[1:4])

[10 15 20]


In [ ]:
# negative silicing
print(data[-1])

25


Mini Task : create a array of student marks  and print
             
             First mark ,Last mark , First three marks , Last three marks

In [ ]:
import numpy as np
marks=np.array([60,45,50,35,65])
print(marks[0])
print(marks[-1])
print(marks[0:3])
print(marks[-3:])

60
65
[60 45 50]
[50 35 65]
